syclop:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  pan_position_controller:
    type: effort_controllers/JointVelocityController
    joint: pan_arm_pan_base_joint
    pid: {p: 10.0, i: 0.0, d: 0.0}
